feat: implement the command `setrange`
OpenAtomFoundation/pikiwidb-raft pull request #103
Opened 2023-12-30 17:25 UTC by jettcc

implement the command `setrange`
The implementation effect is as follows:
<img width="344" alt="CleanShot 2023-12-31 at 01 20 49@2x" src="https://github.com/OpenAtomFoundation/pikiwidb/assets/51713304/b3a13b97-33b6-45f7-96cb-7cdb36147a57">

The following image is the implementation of the same command in `Redis`:
<img width="243" alt="CleanShot 2023-12-31 at 01 22 54@2x" src="https://github.com/OpenAtomFoundation/pikiwidb/assets/51713304/8bbd38e7-2b1e-43dc-b2d2-5de047bf3786">

2023-12-31 14:50 UTC, AlexStocks submitted a review, later dismissed

2024-01-04 02:39 UTC, 578223592 commented on src/cmd_kv.cc
> +    : BaseCmd(name, arity, kCmdFlagsReadonly, kAclCategoryRead | kAclCategoryString) {}
可能：kCmdFlagsWrite, kAclCategoryWrite更合适

2024-01-04 02:40 UTC, 578223592 commented
https://github.com/OpenAtomFoundation/pikiwidb/issues/30#issuecomment-1858822631
这个小工具可以方便对比redis和pikiwidb的输出

2024-01-04 03:49 UTC, jettcc commented on src/cmd_kv.cc
> +    : BaseCmd(name, arity, kCmdFlagsReadonly, kAclCategoryRead | kAclCategoryString) {}
坏，copilot 自动生成错了

2024-01-18 06:39 UTC, 578223592 commented
添加go test
参考：https://github.com/OpenAtomFoundation/pika/blob/unstable/tests/integration

2024-01-22 06:00 UTC, 578223592 requested changes

2024-01-22 06:00 UTC, 578223592 commented on src/store.cc
请问为什么要在`PStore`中实现逻辑，不在`setrange`中实现

2024-01-22 06:00 UTC, 578223592 commented on src/store.cc
> +  PError err = getValueByType(key, old_value, kPTypeString);
blackwidow不是引入了，可以直接用那提供的api

2024-01-22 07:27 UTC, jettcc commented on src/store.cc
因为我开发这个命令的时候，还没有引入blackwidow

2024-01-22 07:46 UTC, 578223592 approved these changes

2024-01-22 08:11 UTC, AlexStocks commented
添加 go test

2024-02-03 11:24 UTC, AlexStocks approved these changes

2024-02-03 11:25 UTC, merged