feat:set command scard
OpenAtomFoundation/pikiwidb-raft pull request #120
Opened 2024-01-09 13:07 UTC by whr1118

![pikiwi](https://github.com/OpenAtomFoundation/pikiwidb/assets/128034558/02b98988-dcaf-4578-bab9-6cf0688224cc)
![redis](https://github.com/OpenAtomFoundation/pikiwidb/assets/128034558/22608c7d-a865-435d-ad88-4879bf824bc6)

2024-01-10 00:35 UTC, 578223592 approved these changes

2024-01-13 11:31 UTC, hero-heng submitted a review, later dismissed

2024-01-13 13:28 UTC, AlexStocks commented
Add go test case

2024-01-22 06:02 UTC, 578223592 requested changes
请补充go的测试

2024-01-22 06:02 UTC, 578223592 commented on src/cmd_set.cc
> +  PError err = PSTORE.GetValueByType(client->Key(), value, kPTypeSet);
现在使用blackwidow了，参考一下已经合进去的set命令

2024-02-03 11:29 UTC, AlexStocks approved these changes

2024-02-03 11:29 UTC, panlei-coder approved these changes

2024-02-03 11:30 UTC, merged