feat: add set cmd smove
OpenAtomFoundation/pikiwidb-raft pull request #124
Opened 2024-01-12 07:38 UTC by super-Pan66

2024-02-03 11:31 UTC, panlei-coder commented
@super-Pan66 解决一下冲突

2024-02-24 11:16 UTC, Centurybbx submitted a review, later dismissed

2024-02-24 11:17 UTC, panlei-coder submitted a review, later dismissed

2024-02-24 12:15 UTC, 578223592 requested changes

2024-02-24 12:15 UTC, 578223592 commented on src/cmd_set.cc
> +    client->SetRes(CmdRes::kErrOther, "smove cmd error");
client->SetRes(CmdRes::kErrOther, "smove cmd error"); 应该直接返回，加一个return

2024-02-26 03:02 UTC, 578223592 submitted a review, later dismissed

2024-02-26 07:05 UTC, AlexStocks approved these changes

2024-02-26 07:05 UTC, merged