Format code.Insert a newline at end of file if missing.
OpenAtomFoundation/pikiwidb-raft pull request #253
Opened 2024-04-01 14:39 UTC by lqxhub

格式化代码,如果文件最后一行没有空行,自动加一个空行, 但是这个clang-format选项需要clang-format16支持,所以没有打开,怕影响CI

2024-04-02 04:59 UTC, dingxiaoshuai123 approved these changes, later dismissed

2024-04-02 11:23 UTC, AlexStocks submitted a review, later dismissed

2024-04-02 11:24 UTC, AlexStocks commented
@lqxhub fix the file confliction

2024-04-02 13:32 UTC, longfar-ncy approved these changes, later dismissed

2024-04-03 03:28 UTC, baerwang requested changes
pls fix conflicts

2024-04-03 03:36 UTC, AlexStocks approved these changes

2024-04-03 03:37 UTC, merged